#!/bin/bash

# Install service to start internet over usb by default

# Check script run with root privilages
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Please run with 'sudo $0' or in 'sudo -s' environment." && exit
fi

cp internetOverUSB.sh /etc/init.d/internetOverUSB.sh
chmod 755 /etc/init.d/internetOverUSB.sh
ln -s /etc/init.d/internetOverUSB.sh /etc/rc5.d/S99internetOverUSB.sh

echo "Reboot with 'reboot now' to test."

